name: haoc
version: 0.1.0.0
github: bungogood/haoc
license: MIT
author: Jonathan Good
maintainer: github@bungogood.com
copyright: 2024 Jonathan Good

extra-source-files:
    - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/bungogood/haoc#readme>

dependencies:
    - base >= 4.7 && < 5
    - optparse-applicative
    - time >= 1.12
    - directory >= 1.3.8
    - filepath >= 1.4.2
    - process >= 1.6.19
    - containers >= 0.6.7
    - split >= 0.2.5

ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints

library:
    source-dirs: src

executables:
    haoc:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haoc

tests:
    haoc-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - haoc
